import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

/**
 * 請求書PDFを生成してダウンロードする
 * 日本語文字化け対策: テーブルヘッダー・ラベルを英語表記にし、
 * Noto Sans JP の CDN フォント埋め込みを試みる。
 * CDN取得に失敗した場合はASCII安全モードにフォールバックする。
 */
export async function generatePDF(data, myInfo) {
  const { client, month, invoiceNo, dueDate, doneTasks, total, year, mon } = data

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  // ===== フォント設定 =====
  // Noto Sans JP の Base64 埋め込みを試みる
  let useJapanese = false
  try {
    useJapanese = await embedNotoSansJP(doc)
  } catch (e) {
    console.warn('Noto Sans JP の埋め込みに失敗しました。ASCII モードで生成します。', e)
  }

  const font = useJapanese ? 'NotoSansJP' : 'helvetica'
  doc.setFont(font)

  // ===== ページ設定 =====
  const pageW = doc.internal.pageSize.getWidth()
  const margin = 18
  const contentW = pageW - margin * 2

  // ===== ヘッダー =====
  // タイトル
  doc.setFontSize(28)
  doc.setTextColor(91, 110, 245) // indigo
  doc.text('INVOICE', margin, 30)

  // サブタイトル
  doc.setFontSize(10)
  doc.setTextColor(107, 114, 128)
  const subTitle = useJapanese
    ? `${year}\u5e74${mon}\u6708\u5206 \u8acb\u6c42\u66f8`
    : `Invoice for ${year}-${mon}`
  doc.text(subTitle, margin, 38)

  // 右側メタ情報
  doc.setFontSize(9)
  doc.setTextColor(75, 85, 99)
  const metaX = pageW - margin
  let metaY = 24
  if (invoiceNo) {
    doc.text(`No: ${invoiceNo}`, metaX, metaY, { align: 'right' })
    metaY += 6
  }
  const today = new Date()
  const todayStr = `${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`
  doc.text(`Issue Date: ${todayStr}`, metaX, metaY, { align: 'right' })
  metaY += 6
  if (dueDate) {
    doc.text(`Due: ${dueDate}`, metaX, metaY, { align: 'right' })
  }

  // 区切り線
  doc.setDrawColor(91, 110, 245)
  doc.setLineWidth(0.5)
  doc.line(margin, 44, pageW - margin, 44)

  // ===== 宛先・送付元 =====
  doc.setFontSize(8)
  doc.setTextColor(107, 114, 128)
  doc.text('BILL TO', margin, 52)
  doc.text('FROM', pageW / 2 + 4, 52)

  doc.setFontSize(10)
  doc.setTextColor(31, 41, 55)

  // 宛先
  let billY = 57
  doc.setFont(font, 'bold')
  doc.text(client.name || '', margin, billY)
  doc.setFont(font, 'normal')
  billY += 5
  if (client.contact) { doc.text(client.contact, margin, billY); billY += 5 }
  if (client.address) { doc.text(client.address, margin, billY, { maxWidth: contentW / 2 - 4 }); billY += 5 }
  if (client.email) { doc.text(client.email, margin, billY); billY += 5 }

  // 送付元
  let fromY = 57
  const fromX = pageW / 2 + 4
  doc.setFont(font, 'bold')
  doc.text(myInfo.name || '(Not set)', fromX, fromY)
  doc.setFont(font, 'normal')
  fromY += 5
  if (myInfo.address) { doc.text(myInfo.address, fromX, fromY, { maxWidth: contentW / 2 - 4 }); fromY += 5 }
  if (myInfo.phone) { doc.text(myInfo.phone, fromX, fromY); fromY += 5 }
  if (myInfo.email) { doc.text(myInfo.email, fromX, fromY); fromY += 5 }

  // ===== テーブル =====
  const tableStartY = Math.max(billY, fromY) + 8

  const rows = doneTasks.map(t => [
    t.name,
    t.due || '',
    `${Number(t.price || 0).toLocaleString()} JPY`,
  ])

  autoTable(doc, {
    startY: tableStartY,
    head: [['Task / Description', 'Date', 'Amount (Tax Incl.)']],
    body: rows,
    margin: { left: margin, right: margin },
    headStyles: {
      fillColor: [91, 110, 245],
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 9,
      font: font,
    },
    bodyStyles: {
      fontSize: 9,
      font: font,
      textColor: [55, 65, 81],
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251],
    },
    columnStyles: {
      0: { cellWidth: 'auto' },
      1: { cellWidth: 28 },
      2: { cellWidth: 36, halign: 'right' },
    },
  })

  // ===== 合計 =====
  const finalY = doc.lastAutoTable.finalY + 6
  doc.setDrawColor(91, 110, 245)
  doc.setLineWidth(0.5)
  doc.line(pageW - margin - 70, finalY, pageW - margin, finalY)
  doc.setFontSize(11)
  doc.setFont(font, 'bold')
  doc.setTextColor(31, 41, 55)
  const totalLabel = useJapanese ? '\u5408\u8a08' : 'Total'
  doc.text(totalLabel, pageW - margin - 70, finalY + 7)
  doc.text(`${Number(total).toLocaleString()} JPY`, pageW - margin, finalY + 7, { align: 'right' })

  // ===== 振込先 =====
  if (myInfo.bank) {
    const bankY = finalY + 18
    doc.setFontSize(8)
    doc.setFont(font, 'bold')
    doc.setTextColor(107, 114, 128)
    const bankLabel = useJapanese ? '\u632f\u8fbc\u5148' : 'Bank Transfer Info'
    doc.text(bankLabel, margin, bankY)
    doc.setFont(font, 'normal')
    doc.setTextColor(55, 65, 81)
    doc.setFontSize(9)
    doc.text(myInfo.bank, margin, bankY + 5, { maxWidth: contentW })
  }

  // ===== ページフッター =====
  doc.setFontSize(8)
  doc.setTextColor(156, 163, 175)
  doc.text('Generated by FL Manager', pageW / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' })

  // ===== ダウンロード =====
  const filename = `invoice_${year}${mon}${invoiceNo ? '_' + invoiceNo.replace(/[^a-zA-Z0-9]/g, '') : ''}.pdf`
  doc.save(filename)
}

/**
 * Noto Sans JP フォントを CDN から取得して jsPDF に登録する
 * 成功したら true を返す
 */
async function embedNotoSansJP(doc) {
  // Google Fonts CSS API から woff2 URL を取得し、Base64 に変換する
  // ただし CORS の関係でブラウザから直接取得できない場合があるため、
  // 失敗したら false を返してフォールバックする
  const fontUrl = 'https://fonts.gstatic.com/s/notosansjp/v52/-F6jfjtqLzI2JPCgQBnw7HFyzSD-AsregP8VFBEj75vY0rw-oME.woff2'

  try {
    const res = await fetch(fontUrl, { mode: 'cors' })
    if (!res.ok) return false
    const buffer = await res.arrayBuffer()
    const base64 = arrayBufferToBase64(buffer)
    doc.addFileToVFS('NotoSansJP-Regular.ttf', base64)
    doc.addFont('NotoSansJP-Regular.ttf', 'NotoSansJP', 'normal')
    doc.addFont('NotoSansJP-Regular.ttf', 'NotoSansJP', 'bold')
    return true
  } catch {
    return false
  }
}

function arrayBufferToBase64(buffer) {
  let binary = ''
  const bytes = new Uint8Array(buffer)
  const chunkSize = 8192
  for (let i = 0; i < bytes.length; i += chunkSize) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunkSize))
  }
  return btoa(binary)
}
